test = {   'name': 'q1_2',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> shifted_array = shift_column(nyse["IBM"], "date", "up");\n>>> assert type(shifted_array) == type(make_array(1,2,3))\n',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> shifted_array = shift_column(nyse["IBM"], "date", "up");\n>>> assert len(shifted_array) == nyse["IBM"].num_rows\n', 'hidden': False, 'locked': False},
                                   {'code': '>>> shifted_array = shift_column(nyse["IBM"], "date", "up");\n>>> assert type(shifted_array.item(-1)) == type(None)\n', 'hidden': False, 'locked': False},
                                   {   'code': '>>> shifted_array = shift_column(nyse["IBM"], "date", "up");\n>>> assert shifted_array.item(0) == nyse["IBM"].column("date").item(1)\n',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
