test = {   'name': 'q1_5',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> assert type(filter_end_of_month(nyse["IBM"])) == type(Table())\n', 'hidden': False, 'locked': False},
                                   {'code': '>>> assert filter_end_of_month(nyse["IBM"]) != nyse["IBM"]\n', 'hidden': False, 'locked': False},
                                   {'code': '>>> assert filter_end_of_month(nyse["IBM"]).num_rows < nyse["IBM"].num_rows\n', 'hidden': False, 'locked': False},
                                   {   'code': '>>> filtered_dates = filter_end_of_month(nyse["IBM"]).column("date");\n>>> assert filtered_dates.item(-1).month != filtered_dates.item(-2).month\n',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> assert filter_end_of_month(nyse["IBM"]).labels == nyse["IBM"].labels\n', 'hidden': False, 'locked': False},
                                   {   'code': '>>> filtered_dates = filter_end_of_month(nyse["IBM"]).column("date");\n>>> assert filtered_dates.item(1) == dt.date(1911, 9, 30)\n',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> filtered_dates = filter_end_of_month(nyse["IBM"]).column("date");\n>>> assert filtered_dates.item(-11) == dt.date(2019, 12, 31)\n',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
